#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if [ -f "$HOME/Brewfile" ]; then
    echo "Updating homebrew bundle"
    brew bundle --global
  fi

  if [ -d "$HOME/.config/iterm2" ]; then
    echo "Setting iTerm preference folder"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.config/iterm2"
  fi

  # setup macos defaults
  if [ -f "$HOME/.macos" ]; then
    echo "Setting macOS defaults"
    . "$HOME/.macos"
  fi

  echo "Installing iterm2 themes"
  open .config/iterm2/GitHub\ Dark\ Dimmed.itermcolors
  open .config/iterm2/GitHub\ Light\ Default.itermcolors
fi

if [ "$system_type" = "Linux" ]; then
  echo "Installing linux packages"
  sudo apt-get update
  sudo apt-get install -y \
    bash \
    bash-completion \
    curl \
    git \
    jq \
    wget \
    zsh \
    zsh-syntax-highlighting \
    zsh-autosuggestions \
fi

# install node if it's missing
if ! command -v node >/dev/null 2>&1; then
  echo "Install latest Nodejs lts"
  curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
fi



echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:thomas-lebeau/.dotfiles.git"
